In [2]:
import pandas as pd

In [5]:
df_fam = pd.read_csv('/mnt/c/Users/Administrator/Desktop/data/Han_SNP4.fam',sep='\t',header=None)
df_fam

                            0                        1  2  3  4  5
0     10100001_ZBYBWS01P29A02  10100001_ZBYBWS01P29A02  0  0  1  1
1     10100003_ZBYBWS01P01A03  10100003_ZBYBWS01P01A03  0  0  2  1
2     10100004_ZBYBWS01P01A04  10100004_ZBYBWS01P01A04  0  0  1  1
3     10100005_ZBYBWS01P01A05  10100005_ZBYBWS01P01A05  0  0  1  1
4     10100006_ZBYBWS01P01A06  10100006_ZBYBWS01P01A06  0  0  1  1
...                       ...                      ... .. .. .. ..
3130  10201049_ZBYBWS02P11H08  10201049_ZBYBWS02P11H08  0  0  1  2
3131  10201050_ZBYBWS02P11H09  10201050_ZBYBWS02P11H09  0  0  2  2
3132  10201051_ZBYBWS02P11H10  10201051_ZBYBWS02P11H10  0  0  1  2
3133  10201052_ZBYBWS02P11H11  10201052_ZBYBWS02P11H11  0  0  2  2
3134  10201053_ZBYBWS02P11H12  10201053_ZBYBWS02P11H12  0  0  1  2

[3135 rows x 6 columns]

In [6]:
# 重命名df_fam
df_fam.columns = ['FID', 'IID', 'PID', 'MID', 'SEX', 'PHENOTYPE']
df_fam

,FID,IID,PID,MID,SEX,PHENOTYPE
0,10100001_ZBYBWS01P29A02,10100001_ZBYBWS01P29A02,0,0,1,1
1,10100003_ZBYBWS01P01A03,10100003_ZBYBWS01P01A03,0,0,2,1
2,10100004_ZBYBWS01P01A04,10100004_ZBYBWS01P01A04,0,0,1,1
3,10100005_ZBYBWS01P01A05,10100005_ZBYBWS01P01A05,0,0,1,1
4,10100006_ZBYBWS01P01A06,10100006_ZBYBWS01P01A06,0,0,1,1
...,...,...,...,...,...,...
3130,10201049_ZBYBWS02P11H08,10201049_ZBYBWS02P11H08,0,0,1,2
3131,10201050_ZBYBWS02P11H09,10201050_ZBYBWS02P11H09,0,0,2,2
3132,10201051_ZBYBWS02P11H10,10201051_ZBYBWS02P11H10,0,0,1,2
3133,10201052_ZBYBWS02P11H11,10201052_ZBYBWS02P11H11,0,0,2,2
3134,10201053_ZBYBWS02P11H12,10201053_ZBYBWS02P11H12,0,0,1,2

In [8]:
df_PCA = pd.read_csv('/mnt/c/Users/Administrator/Desktop/data/Han_SNP4.eigenvec',sep=' ',header=None)
df_PCA

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,10100001_ZBYBWS01P29A02,10100001_ZBYBWS01P29A02,-0.001097,0.004399,-0.000746,-0.010201,-0.006379,0.017902,0.005179,0.002116,...,0.008639,0.021965,0.000208,0.034165,-0.011518,0.004305,-0.006672,-0.003167,0.001554,0.017220
1,10100003_ZBYBWS01P01A03,10100003_ZBYBWS01P01A03,0.001694,-0.002134,-0.003711,0.017165,-0.037159,-0.026216,-0.007851,0.010448,...,-0.005031,0.011309,0.000964,-0.024479,-0.004709,-0.031393,0.023754,-0.005740,-0.005431,-0.010947
2,10100004_ZBYBWS01P01A04,10100004_ZBYBWS01P01A04,0.000707,-0.003424,0.003840,0.003797,-0.007465,-0.016427,0.002266,0.005725,...,-0.010955,-0.015935,0.013662,-0.006503,0.001943,-0.013303,0.000590,-0.000476,-0.003818,-0.003212
3,10100005_ZBYBWS01P01A05,10100005_ZBYBWS01P01A05,-0.004664,0.007483,0.003895,0.005313,0.004956,0.011892,-0.005586,-0.004404,...,-0.022754,-0.006619,0.002006,0.021338,-0.006347,0.001725,0.004759,0.018304,-0.002592,-0.000050
4,10100006_ZBYBWS01P01A06,10100006_ZBYBWS01P01A06,-0.003999,0.009350,0.005391,-0.002577,-0.004146,0.001570,0.008650,0.002044,...,-0.004071,-0.004685,0.002884,-0.001301,0.009741,-0.004303,0.001425,-0.006345,0.003837,-0.010674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3130,10201049_ZBYBWS02P11H08,10201049_ZBYBWS02P11H08,0.012346,-0.043375,0.019958,-0.028160,-0.012830,0.003344,0.001091,-0.014221,...,0.000189,-0.007303,-0.003723,0.004248,0.006277,0.015027,-0.018764,-0.001715,-0.007417,-0.010462
3131,10201050_ZBYBWS02P11H09,10201050_ZBYBWS02P11H09,0.025534,-0.082719,0.018497,-0.053552,0.010983,0.019110,-0.012126,-0.006015,...,-0.005191,-0.000879,-0.004245,0.010895,-0.001694,-0.010324,0.007192,0.045633,0.000339,0.005058
3132,10201051_ZBYBWS02P11H10,10201051_ZBYBWS02P11H10,-0.003203,0.001074,0.002965,-0.001069,-0.009091,0.009598,0.010315,0.011325,...,0.027719,0.005291,-0.013549,-0.007033,0.007457,0.009873,-0.003611,0.000340,-0.003111,-0.006425
3133,10201052_ZBYBWS02P11H11,10201052_ZBYBWS02P11H11,-0.004369,0.007785,-0.005612,-0.007800,-0.016683,0.003931,0.009565,0.011582,...,-0.000419,-0.008340,-0.006147,0.006729,0.013913,0.020046,0.000288,-0.036586,-0.017976,-0.004549
3134,10201053_ZBYBWS02P11H12,10201053_ZBYBWS02P11H12,0.001478,-0.011599,-0.004495,0.023575,-0.018405,-0.005205,0.021516,0.013677,...,0.022905,-0.004480,-0.015359,-0.009781,0.012292,0.001031,0.006763,0.013329,0.003948,0.021968

In [9]:
# 重命名df_PCA
df_PCA.columns = ['FID', 'IID'] + [f'PC{i+1}' for i in range(df_PCA.shape[1] - 2)]
df_PCA

,FID,IID,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,...,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20
0,10100001_ZBYBWS01P29A02,10100001_ZBYBWS01P29A02,-0.001097,0.004399,-0.000746,-0.010201,-0.006379,0.017902,0.005179,0.002116,...,0.008639,0.021965,0.000208,0.034165,-0.011518,0.004305,-0.006672,-0.003167,0.001554,0.017220
1,10100003_ZBYBWS01P01A03,10100003_ZBYBWS01P01A03,0.001694,-0.002134,-0.003711,0.017165,-0.037159,-0.026216,-0.007851,0.010448,...,-0.005031,0.011309,0.000964,-0.024479,-0.004709,-0.031393,0.023754,-0.005740,-0.005431,-0.010947
2,10100004_ZBYBWS01P01A04,10100004_ZBYBWS01P01A04,0.000707,-0.003424,0.003840,0.003797,-0.007465,-0.016427,0.002266,0.005725,...,-0.010955,-0.015935,0.013662,-0.006503,0.001943,-0.013303,0.000590,-0.000476,-0.003818,-0.003212
3,10100005_ZBYBWS01P01A05,10100005_ZBYBWS01P01A05,-0.004664,0.007483,0.003895,0.005313,0.004956,0.011892,-0.005586,-0.004404,...,-0.022754,-0.006619,0.002006,0.021338,-0.006347,0.001725,0.004759,0.018304,-0.002592,-0.000050
4,10100006_ZBYBWS01P01A06,10100006_ZBYBWS01P01A06,-0.003999,0.009350,0.005391,-0.002577,-0.004146,0.001570,0.008650,0.002044,...,-0.004071,-0.004685,0.002884,-0.001301,0.009741,-0.004303,0.001425,-0.006345,0.003837,-0.010674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3130,10201049_ZBYBWS02P11H08,10201049_ZBYBWS02P11H08,0.012346,-0.043375,0.019958,-0.028160,-0.012830,0.003344,0.001091,-0.014221,...,0.000189,-0.007303,-0.003723,0.004248,0.006277,0.015027,-0.018764,-0.001715,-0.007417,-0.010462
3131,10201050_ZBYBWS02P11H09,10201050_ZBYBWS02P11H09,0.025534,-0.082719,0.018497,-0.053552,0.010983,0.019110,-0.012126,-0.006015,...,-0.005191,-0.000879,-0.004245,0.010895,-0.001694,-0.010324,0.007192,0.045633,0.000339,0.005058
3132,10201051_ZBYBWS02P11H10,10201051_ZBYBWS02P11H10,-0.003203,0.001074,0.002965,-0.001069,-0.009091,0.009598,0.010315,0.011325,...,0.027719,0.005291,-0.013549,-0.007033,0.007457,0.009873,-0.003611,0.000340,-0.003111,-0.006425
3133,10201052_ZBYBWS02P11H11,10201052_ZBYBWS02P11H11,-0.004369,0.007785,-0.005612,-0.007800,-0.016683,0.003931,0.009565,0.011582,...,-0.000419,-0.008340,-0.006147,0.006729,0.013913,0.020046,0.000288,-0.036586,-0.017976,-0.004549
3134,10201053_ZBYBWS02P11H12,10201053_ZBYBWS02P11H12,0.001478,-0.011599,-0.004495,0.023575,-0.018405,-0.005205,0.021516,0.013677,...,0.022905,-0.004480,-0.015359,-0.009781,0.012292,0.001031,0.006763,0.013329,0.003948,0.021968

In [23]:
df_out = pd.read_csv('/mnt/c/Users/Administrator/Desktop/data/Han_SNP4.out',sep=r'\s+')
mask = df_out['p-value'] <= 0.05
# 在原 df_out 上添加新列，仅针对满足条件的行
df_out.loc[mask, 'PC_value'] = 'PC' + df_out.loc[mask, '#N'].astype(str)
# 如果你只想保留显著的部分，再切片
df_out_sig = df_out.loc[mask]
df_out_sig

   #N  eigenvalue  difference  twstat       p-value    effect.   n PC_value
0   1     9.01507         NaN   5.045  2.053330e-05     54.743 NaN      PC1
1   2     6.25038    -2.76469   8.676  3.283230e-09    129.331 NaN      PC2
2   3     3.15546    -3.09492   6.822  2.212350e-07    955.073 NaN      PC3
3   4     2.69216    -0.46330   4.909  2.836100e-05   1928.437 NaN      PC4
4   5     2.40933    -0.28283   1.155  3.900070e-02   3183.600 NaN      PC5
5   6     2.37554    -0.03379   2.755  2.720780e-03   3964.370 NaN      PC6
6   7     2.26718    -0.10836   1.724  1.635870e-02   5761.556 NaN      PC7
7   8     2.20738    -0.05980   1.822  1.396040e-02   7888.764 NaN      PC8
8   9     2.14370    -0.06368   1.210  3.597150e-02  11349.293 NaN      PC9
9  10     2.11658    -0.02712   2.589  3.698380e-03  15932.218 NaN     PC10

In [26]:
# 将符合要求的PC值（即df_out_sig中的PC_value列）从df_PCA中对应的列提取出来
pc_columns = df_out_sig['PC_value'].unique()
df_PCAS = df_PCA[['FID', 'IID'] + list(pc_columns)]
df_PCAS

,FID,IID,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10
0,10100001_ZBYBWS01P29A02,10100001_ZBYBWS01P29A02,-0.001097,0.004399,-0.000746,-0.010201,-0.006379,0.017902,0.005179,0.002116,0.011527,-0.005109
1,10100003_ZBYBWS01P01A03,10100003_ZBYBWS01P01A03,0.001694,-0.002134,-0.003711,0.017165,-0.037159,-0.026216,-0.007851,0.010448,-0.001362,0.027994
2,10100004_ZBYBWS01P01A04,10100004_ZBYBWS01P01A04,0.000707,-0.003424,0.003840,0.003797,-0.007465,-0.016427,0.002266,0.005725,-0.000922,0.002025
3,10100005_ZBYBWS01P01A05,10100005_ZBYBWS01P01A05,-0.004664,0.007483,0.003895,0.005313,0.004956,0.011892,-0.005586,-0.004404,-0.007652,0.013315
4,10100006_ZBYBWS01P01A06,10100006_ZBYBWS01P01A06,-0.003999,0.009350,0.005391,-0.002577,-0.004146,0.001570,0.008650,0.002044,-0.007368,-0.007971
...,...,...,...,...,...,...,...,...,...,...,...,...
3130,10201049_ZBYBWS02P11H08,10201049_ZBYBWS02P11H08,0.012346,-0.043375,0.019958,-0.028160,-0.012830,0.003344,0.001091,-0.014221,-0.001613,-0.038702
3131,10201050_ZBYBWS02P11H09,10201050_ZBYBWS02P11H09,0.025534,-0.082719,0.018497,-0.053552,0.010983,0.019110,-0.012126,-0.006015,0.002862,-0.001089
3132,10201051_ZBYBWS02P11H10,10201051_ZBYBWS02P11H10,-0.003203,0.001074,0.002965,-0.001069,-0.009091,0.009598,0.010315,0.011325,-0.013120,0.000122
3133,10201052_ZBYBWS02P11H11,10201052_ZBYBWS02P11H11,-0.004369,0.007785,-0.005612,-0.007800,-0.016683,0.003931,0.009565,0.011582,-0.009913,0.005123
3134,10201053_ZBYBWS02P11H12,10201053_ZBYBWS02P11H12,0.001478,-0.011599,-0.004495,0.023575,-0.018405,-0.005205,0.021516,0.013677,-0.011576,0.013908

In [28]:
# 打印
print('共提取了{}个样本的{}个主成分'.format(df_PCAS.shape[0], len(pc_columns)))
print('分别是:', ', '.join(pc_columns))

共提取了3135个样本的10个主成分
分别是: PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10

In [ ]:
# 准备生成`.cov`文件
# todo,示例如下
# # 带表头的 .cov 文件
# FID              IID              PC1       PC2   Age
# 10100001_sample1 10100001_sample1 -0.1234   0.2345 40
# 10100003_sample2 10100003_sample2  0.5678  -0.3456 42
df_PCAS.to_csv('/mnt/c/Users/Administrator/Desktop/conf/Han_SNP4.cov', sep='\t', index=False, header=True)